name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Helo World!"
          echo "This is run using | (pipe symbol)"
      - name: Print goodbye
        run: echo "Done -Bye!"
